### ISSUE TITLE
asciinema.org returns 500

### ISSUE THREAD

**Issue by utdemir** [asciinema/asciinema-server#368]
It seems like the entire asciinema.org is down for a while, every request returns HTTP 500:

```
$ curl -v https://asciinema.org
...
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 500 
< cache-control: max-age=0, private, must-revalidate
< content-type: text/html; charset=utf-8
< cross-origin-window-policy: deny
< date: Mon, 14 Dec 2020 02:09:16 GMT
< server: nginx
< x-content-type-options: nosniff
< x-download-options: noopen
< x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
< x-request-id: FlBzONH_zH-NFQAAE3OB
< x-xss-protection: 1; mode=block
< content-length: 21
< 
* Connection #0 to host asciinema.org left intact
Internal Server Error
```

**Comment by utdemir** [comment]
Seems to be good now.

**Comment by rcorre** [comment]
Seeing this again with `asciinema upload`:

```
✦ ❯ asciinema upload lasr.asciinema 
Error: HTTP status server error (500 Internal Server Error) for url (https://asciinema.org/api/asciicasts)
```

Using `asciinema 3.0.0-rc.5`.

**Comment by rcorre** [comment]
I think I might have corrupted it by accident ... I tried again with a fresh recording and it work. However, it would be nice if an invalid recording returned a 400 instead of a 500, so the user knows they did something wrong and doesn't assume there's a problem with the server. I'm happy to take a stab at that if you agree.

**Comment by ku1ik** [comment]
Yeah, I agree. It's just some parsing error I haven't accounted for. Should be easy to handle.

**Comment by ku1ik** [comment]
@rcorre If you’d like to have a stab at it:

The crash happened in lib/asciinema/recordings/asciicast/v3.ex , in `event_stream/1` (which is called via `fetch_metadata` -> `get_duration`). One of the 2 `Jason.decode!` invocations crashed due to malformed json. 

So we’d need to update the whole chain of those functions to return result tuples I guess.
