### ISSUE TITLE
Feature: Add custom font support.

### ISSUE THREAD

**Issue by pozgo** [asciinema/asciinema-server#383]
Lots of us are using `zsh` and `powerlevel10k` + `MesloLGS NF` or other custom fonts so the terminal looks nice. 

Please add an option in the configuration to specify the font which will be used when rendering. 

So far I'm using `terminalizer` which gives me that option but I would love to move back to `asciinema` but lack of this feature is a deal breaker ATM 

Link to [terminalizer](https://github.com/faressoft/terminalizer)

**Comment by sickill** [comment]
Somewhat related: https://github.com/asciinema/asciinema-player/issues/140

**Comment by MrWormHole** [comment]
is it so hard to add MesloGS NF support for asciinema server? I see so many issues are raised, yet there is no elixir guru who can spend time on this

**Comment by xsebek** [comment]
@sickill since it is possible to use custom fonts in JavaScript, how hard would it be to use that feature in the server?

I am not a web dev, but from the discussion and this tutorial ([link](https://designbundles.net/design-school/using-custom-web-fonts)), it looks like the asciinema website would have to bundle one nerd font and allow setting that in the player.

For example, if the `MesloGS NF` font proposed by @MrWormHole was stored as `https://asciinema.org/font/meslonf.woff`, then in the webpage there would have to be:
```css
@font-face
{
font-family: meslonf;
src: url('font/meslonf.woff') format('woff’);
}
```
and the `font-family-monospace` (or the `terminalFontFamily` of the player) would change to:
```
meslonf,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace
```

I assume there would need to be some way to differentiate what font to prefer, so supporting `?font=meslonf` would be nice.
Adding a button like `Use Nerd font` should be easy enough.

---

Thanks for making such a great tool @sickill. :+1:  I guess I could create my own JavaScript player with the font set, but it would be neat to have this function on the default webpage and not have to learn JS. :sweat_smile:

**Comment by MrWormHole** [comment]
I still think the issue is related to terminal recorder, for instance when I turn the format into gif for zsh + powerlevel10k theme, it gives square brackets. Maybe a specific flag terminal font can be supplied? 

I use rust based agg for converting asciinema format to gif

I am missing something but not sure

**Comment by xsebek** [comment]
@MrWormHole in the linked issue asciinema/asciinema-player#140 someone linked a [blog post](https://www.tonylykke.com/posts/2018/06/18/custom-fonts-in-asciinema/) on how to fix this if you are self-hosting and it looks like the squares are expected:
|[![Custom Fonts in Asciinema](https://user-images.githubusercontent.com/44544735/193419220-a7462960-9f1f-4d07-8ca1-78232f76ccad.png)](https://www.tonylykke.com/posts/2018/06/18/custom-fonts-in-asciinema/)|
|-|

**Comment by MrWormHole** [comment]
I run `asciiname rec` then I get URL at the end of the record. Then I run `agg <asciinema-URL> ./here.gif` it essentially downloads the gif from asciinema and turns into gif. You can also do directly from your cast file to gif file https://github.com/asciinema/agg @xsebek

**Comment by MrWormHole** [comment]
ooooohhh sweet baby jesus @xsebek you solved it, I did this and it works beautifully now

agg demo.cast ./my.gif --font-family="MesloLGS NF"
![my](https://user-images.githubusercontent.com/22800416/193420487-1bfe7c13-27b0-49d8-8d12-c8d120010ade.gif)

**Comment by xsebek** [comment]
@MrWormHole I disagree - if we could afford ~750kB `mesloNF.woff` (current fonts directory is 1.2MB) then that would allow supporting any Powerline or NerdFont recording since all the extra glyphs are shared between fonts.

Maybe there is some CSS magic that would only pull this asset when the URI contains `?font=mesloNF` or something. 

Good to know about [`agg`](https://github.com/asciinema/agg), I expected the feature to be part of `asciinema` and Googling pointed me to [savage13/agg](https://github.com/savage13/agg). :smile:

**Comment by MrWormHole** [comment]
@xsebek if the frontend was using code splitting for font loading, this wouldn't be a problem, if it is built in MVC ways, they can not do stylesheet loading based on the page dynamically. Therefore have to load the font on every page.

The example you mentioned is also possible but requires code splitting on CSS/SCSS/LESS which requires modern tooling like webpack/rollup/esbuild (static bundle optimizers)

**Comment by sickill** [comment]
As you figured earlier, font rendering is not related to terminal recorder, which itself knows nothing about fonts. It only saves terminal output stream to a file. All the issues with font rendering are in frontends (asciinema-player, agg).

I've implemented support for Nerd Fonts (opt-in, for each uploaded recording) in #412. It brings Fira Code and JetBrains Mono variants for start. Indeed including every single Nerd Font variant I'd rather avoid, but let's see if we can get by with these 2. In the end people request Nerd Font support mostly for icons/symbols, not for specific font faces.

Regarding conditional fetching of fonts - in fact browsers only fetch custom font faces that are in use on the page. So having all necessary `@font-face` definitions in CSS is harmless. #412 allows enabling Nerd Font per recording for those who need it, but for majority of recordings the actual font files won't be fetched. At least it looks like this according to my tests.

**Comment by sickill** [comment]
Also, checkout latest agg - it has lots of font related improvements as well: https://github.com/asciinema/agg#fonts

**Comment by sickill** [comment]
Nerd Font support is now live on asciinema.org

![image](https://user-images.githubusercontent.com/17589/229781586-fa781c32-266c-46b2-8bfe-16e45ca0c1b4.png)

**Comment by joaco05** [comment]
You might wanna update the Nerd Fonts, some gylphs are missing
