### ISSUE TITLE
On website, some lines are partially covered

### ISSUE THREAD

**Issue by DUOLabs333** [asciinema/asciinema-server#390]
Arch Linux with Firefox. For some reason, each of the lines are hidden partially.

Example: https://asciinema.org/a/476732

![image](https://user-images.githubusercontent.com/49244768/158274552-e7dd95a4-0257-408b-a7ba-886a998077e0.png)

**Comment by sickill** [comment]
It happens so that I use Arch and Firefox too :) This is how it looks for me:

![image](https://user-images.githubusercontent.com/17589/160301520-0daa9b75-37c1-4d7f-81c0-45b51fb08f39.png)

Looks like the font measurement doesn't work in your case for some reason :thinking:  Do you experience this for all the recordings on asciinema.org?

**Comment by DUOLabs333** [comment]
Yes, no matter what page I use, even if it's embedded.

**Comment by sickill** [comment]
Ok. Let's check what font is actually used for rendering in your case. Can you inspect one of the lines with text in the player and then switch to the Fonts inspect as seen here?

![image](https://user-images.githubusercontent.com/17589/160301918-a3071a55-85c0-41ce-a538-745409d11ab9.png)

**Comment by DUOLabs333** [comment]
For my example, it uses Noto Sans Mono.

**Comment by DUOLabs333** [comment]
I just set it in Preferences.

**Comment by sickill** [comment]
Got it, thanks.

This problem is not fixable in the current text-based renderer. We can keep this issue open for the time being though.
