### ISSUE TITLE
script tag to embed player generated by share menu doesn't work

### ISSUE THREAD

**Issue by mowhits** [asciinema/asciinema-server#435]
the script tag generated in the "share this recording" menu didn't allow me to embed the player on my site.

here's the tag it generated that doesn't embed: `<script src="https://asciinema.org/a/6ninhmGNsEouSlNDOFXSbrvB9.js" id="asciicast-651783" async="true"></script>`
and here's what is displayed:
> To protect your security, asciinema.org will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

but oddly enough, if i change the `id` from `asciicast-numbers` like in the broken tag to `asciicast-filename`, or  `<script src="https://asciinema.org/a/6ninhmGNsEouSlNDOFXSbrvB9.js" id="asciicast-6ninhmGNsEouSlNDOFXSbrvB9" async="true"></script>`, it works.  why is this so?

**Comment by ku1ik** [comment]
Thanks for reporting. This was super odd at first, but I've found the problem.

The thing is, the `id` is used to load the recording inside the frame, and given your recording has not been made public the lookup by bare numerical ID returns 404, because non-public recordings must be addressed via the secret token. The fix should be simple though.
